#!/bin/sh
echo "Mounting filesystems..."
mount -a

echo "Configuring loopback..."
ifconfig lo 127.0.0.1

echo "Loading ethernet driver..."
modprobe 8139cp

echo "Enabling ethernet interface..."
ifconfig eth0 up

echo "Configuring network..."
udhcpc eth0

echo "Setting hostname..."
hostname $(cat /etc/hostname)

echo "Starting login..."
clear
getty 115200 tty1
